#!/usr/bin/env bash
#
# initialize.sh — runs on the HOST (devcontainer.json `initializeCommand`),
# before the Compose stack is created.
#
# Two jobs:
#
#   1. Guarantee that every bind-mount source declared in compose.yaml exists.
#      Docker creates a root-owned *directory* in place of a missing source,
#      which then shadows the socket (or file) the container expects — and the
#      container starts silently broken instead of failing loudly.
#
#   2. Write .devcontainer/.env with the host paths compose.yaml interpolates.
#      devcontainer.json could read the host environment directly through
#      ${localEnv:...}; a Compose file cannot. An undefined variable there
#      expands to the empty string, which turns a mount source into a bogus
#      absolute path — so the values are resolved here, once, explicitly.
#
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --- Host git identity and GitHub token (mounted read-only) ---
# Both are bind-mounted as FILES. If either is missing, Docker would create a
# root-owned directory at that path in your home directory — breaking git on
# the host, not just in the container.
[ -e "${HOME}/.gitconfig" ] || touch "${HOME}/.gitconfig"
if [ ! -s "${HOME}/.gh_token_manaiba" ]; then
  touch "${HOME}/.gh_token_manaiba"
  echo "initialize.sh: ~/.gh_token_manaiba is missing or empty —" \
       "private clones will fail. See README → GitHub authentication." >&2
fi

# --- Host desktop sockets: microphone (PulseAudio/PipeWire) and Wayland ---
# On a host with no desktop session (a CI runner, macOS, a plain SSH box) the
# placeholders below keep the mounts valid, and the container simply comes up
# without audio/clipboard instead of refusing to start.
runtime_dir="${XDG_RUNTIME_DIR:-}"
if [ -z "${runtime_dir}" ] || [ ! -d "${runtime_dir}" ]; then
  runtime_dir="/tmp/inatrace-no-desktop"
  echo "initialize.sh: XDG_RUNTIME_DIR unset or missing —" \
       "the container will start without microphone/clipboard/headed browser." >&2
fi

mkdir -p "${runtime_dir}/pulse"
[ -e "${runtime_dir}/pulse/native" ] || touch "${runtime_dir}/pulse/native"

# Keep this display name in sync with the wayland mount in compose.yaml.
# If your session is not wayland-0 (check `echo $WAYLAND_DISPLAY`), change it
# in BOTH places.
[ -e "${runtime_dir}/wayland-0" ] || touch "${runtime_dir}/wayland-0"

# --- .env consumed by compose.yaml (generated; do not edit by hand) ---
{
  printf '# Generated by .devcontainer/initialize.sh — do not edit.\n'
  printf '# Host paths interpolated into the bind mounts in compose.yaml.\n'
  printf 'HOST_HOME=%s\n' "${HOME}"
  printf 'HOST_RUNTIME_DIR=%s\n' "${runtime_dir}"
} > "${here}/.env"
